# Generated by Django 4.2.4 on 2023-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
