# Generated by Django 4.2.5 on 2023-10-04 00:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to=main.models.item.content_file_name),
        ),
    ]
