# Generated by Django 4.2.5 on 2023-10-04 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_item_harga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="harga",
        ),
    ]
